from building import *

# get current directory
cwd     = GetCurrentDir()

# The set of source files associated with this SConscript file.
src     = Glob('rtc.c')
src    += Glob('date.c')
src    += Glob('datatime.c')
path = [cwd]

group = DefineGroup('rtc', src, depend = [''], CPPPATH = path)

Return('group')
