
#ifndef __SYSDEF_H__
#define __SYSDEF_H__

#define 	XMODEM_DATA_SIZE        128
#define 	BOOTLOADER_SIZE         0x6000UL//应用层地址24k//(24kUL*1024UL)
#define 	APP_DEVICE_INFO_SIZE 	1024
#define 	APPLICATION_SIZE  		0x19000//100k空间


#define 	FLASH_START_ADDR   0x08000000
#define 	APP_DEVICE_INFO_START_ADDR (FLASH_START_ADDR+BOOTLOADER_SIZE)


#define 	FLASH_ADDR_UPDATEFLAG_ADDR (APP_DEVICE_INFO_START_ADDR+XMODEM_DATA_SIZE)
#define 	APPLICATION_START_ADDR  (APP_DEVICE_INFO_START_ADDR+APP_DEVICE_INFO_SIZE)



#define 	EXTERNFLASH_BIN_START_ADDR	0x3800//从14k开始
#define 	EXTERNFLASH_BIN_SIZE		0x19000//100k空间

#endif
