
#ifndef __SYSDEF_H__
#define __SYSDEF_H__

#define 	XMODEM_DATA_SIZE        128
#define 	BOOTLOADER_SIZE         0x4000UL//应用层地址24k//(24kUL*1024UL)
#define 	APP_DEVICE_INFO_SIZE 	1024
#define 	APPLICATION_SIZE  		0x19000//100k空间


#define 	FLASH_START_ADDR   0x08000000
#define		APP_FLASH_ADDR		( FLASH_START_ADDR + BOOTLOADER_SIZE ) 
//#define 	APP_DEVICE_INFO_START_ADDR (FLASH_START_ADDR+BOOTLOADER_SIZE)


//#define 	FLASH_ADDR_UPDATEFLAG_ADDR (APP_DEVICE_INFO_START_ADDR+XMODEM_DATA_SIZE)
//#define 	APPLICATION_START_ADDR  (APP_DEVICE_INFO_START_ADDR+APP_DEVICE_INFO_SIZE)



//#define 	EXTERNFLASH_BIN_START_ADDR	0x3800//从14k开始
//#define 	EXTERNFLASH_BIN_SIZE		0x19000//100k空间

// 外部Flash
#define  EX_FLASH_SECTOR_SIZE	4096	//外部的闪存页大小为4KB，擦除的最小单位

#define  EX_FLASH_CFG_INFO_ADDR			0
#define  EX_FLASH_CFG_INFO_SIZE			EX_FLASH_SECTOR_SIZE

#define  EX_FLASH_CFG_PDO_INFO_ADDR		(EX_FLASH_CFG_INFO_ADDR + EX_FLASH_CFG_INFO_SIZE)
#define  EX_FLASH_CFG_PDO_INFO_SIZE		EX_FLASH_SECTOR_SIZE

#define  EX_FLASH_CFG_DBG_INFO_ADDR		(EX_FLASH_CFG_PDO_INFO_ADDR + EX_FLASH_CFG_PDO_INFO_SIZE)
#define  EX_FLASH_CFG_DBG_INFO_SIZE		EX_FLASH_SECTOR_SIZE

//起始地址在6k
#define	 EX_FLASH_LOG_AREA_ADDR			(EX_FLASH_CFG_DBG_INFO_ADDR + EX_FLASH_CFG_DBG_INFO_SIZE)
#define	 EX_FLASH_LOG_AREA_SIZE			0x2000	//8k

//起始地址在14k
#define	 EX_FLASH_BIN_AREA_ADDR			(EX_FLASH_LOG_AREA_ADDR + EX_FLASH_LOG_AREA_SIZE + 3 * EX_FLASH_SECTOR_SIZE )
#define	 EX_FLASH_BIN_AREA_SIZE			0x20000	//64k












#endif
